# generated by cabal-rpm-0.11.1
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name persistent-sqlite
%global pkgver %{pkg_name}-%{version}

%bcond_with tests

Name:           ghc-%{pkg_name}
Version:        2.6.3
Release:        1%{?dist}
Summary:        Backend for the persistent library using sqlite3

License:        MIT
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-conduit-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-microlens-th-devel
BuildRequires:  ghc-monad-control-devel
BuildRequires:  ghc-monad-logger-devel
BuildRequires:  ghc-old-locale-devel
BuildRequires:  ghc-persistent-devel
BuildRequires:  ghc-resource-pool-devel
BuildRequires:  ghc-resourcet-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-transformers-devel
BuildRequires:  ghc-unordered-containers-devel
BuildRequires:  glibc-devel%{?_isa}
%if %{with tests}
BuildRequires:  ghc-hspec-devel
BuildRequires:  ghc-persistent-template-devel
BuildRequires:  ghc-temporary-devel
%endif
# End cabal-rpm deps
BuildRequires:  sqlite-devel

%description
This package includes a thin sqlite3 wrapper based on the direct-sqlite
package.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
Requires:       %{name}%{?_isa} = %{version}-%{release}
# Begin cabal-rpm deps:
Requires:       glibc-devel%{?_isa}
# End cabal-rpm deps
# Due to https://ghc.haskell.org/trac/ghc/ticket/9498
Requires:       sqlite-devel

%description devel
This package provides the Haskell %{pkg_name} library development
files.


%prep
%setup -q -n %{pkgver}
cabal-tweak-flag systemlib True


%build
%ghc_lib_build


%install
%ghc_lib_install


%check
%cabal_test


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%license LICENSE


%files devel -f %{name}-devel.files
%doc ChangeLog.md


%changelog
* Mon Dec 11 2017 David Shea <dshea@redhat.com> - 2.6.3-1
- Update to persistent-sqlite-2.6.3
- Add a fix from fedpkg for the libsqlite dependency

* Thu Nov 16 2017 David Shea <dshea@redhat.com> - 2.6.2-3
- Rebuild against a new persistent

* Tue Sep 12 2017 David Shea <dshea@redhat.com> - 2.6.2-2
- Rebuild against the Fedora version of ghc-microlens

* Wed Jul 26 2017 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 2.6.2-1
- spec file generated by cabal-rpm-0.11.1
