# generated by cabal-rpm-0.11.2
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name haskell-gi-overloading
%global pkgver %{pkg_name}-%{version}

Name:           ghc-%{pkg_name}
Version:        1.0
Release:        1%{?dist}
Summary:        Overloading support for haskell-gi

License:        BSD
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros

%description
Control overloading support in haskell-gi generated bindings.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}

%description devel
This package provides the Haskell %{pkg_name} library
development files.


%prep
%setup -q -n %{pkgver}


%build
%ghc_lib_build_without_haddock


%install
%ghc_lib_install
mv %{buildroot}%{_ghcdocdir}{,-devel}


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files devel -f %{name}-devel.files
%license LICENSE
%doc ChangeLog.md README.md


%changelog
* Tue Sep 12 2017 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 1.0-1
- spec file generated by cabal-rpm-0.11.2
