# generated by cabal-rpm-0.11.1
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name microlens
%global pkgver %{pkg_name}-%{version}

Name:           ghc-%{pkg_name}
Version:        0.4.8.0
Release:        1%{?dist}
Summary:        A tiny lens library with no dependencies. If you're writing an app, you probably want microlens-platform, not this

License:        BSD
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros

%description
NOTE: If you're writing an app, you probably want
<http://hackage.haskell.org/package/microlens-platform microlens-platform> – it
has the most features. <http://hackage.haskell.org/package/microlens microlens>
is intended more for library writers who want a tiny lens library (after all,
lenses are pretty useful for everything, not just for updating records!).

This library is an extract from <http://hackage.haskell.org/package/lens lens>
(with no dependencies). It's not a toy lenses library, unsuitable for “real
world”, but merely a small one. It is compatible with lens, and should have
same performance. It also has better documentation.

There's a longer readme <https://github.com/aelve/microlens#readme on Github>.
It has a migration guide for lens users, a description of other packages in the
family, a discussion of other lens libraries you could use instead, and so on.

Here are some usecases for this library:

* You want to define lenses or traversals in your own library, but don't want
to depend on lens. Having lenses available often make working with a library
more pleasant.

* You just want to be able to use lenses to transform data (or even just use
'over _1' to change the first element of a tuple).

* You are new to lenses and want a small library to play with.

However, don't use this library if:

* You need 'Iso's, 'Prism's, indexed traversals, or actually anything else
which isn't defined here (tho some indexed functions are available elsewhere –
containers and vector provide them for their types, and
<http://hackage.haskell.org/package/ilist ilist> provides indexed functions for
lists).

* You want a library with a clean, understandable implementation (in which case
you're looking for <http://hackage.haskell.org/package/lens-simple
lens-simple>).

As already mentioned, if you're writing an application which uses lenses more
extensively, look at <http://hackage.haskell.org/package/microlens-platform
microlens-platform> – it combines features of most other microlens packages
(<http://hackage.haskell.org/package/microlens-mtl microlens-mtl>,
<http://hackage.haskell.org/package/microlens-th microlens-th>,
<http://hackage.haskell.org/package/microlens-ghc microlens-ghc>).

If you want to export getters or folds and don't mind the
<http://hackage.haskell.org/package/contravariant contravariant> dependency,
please consider using <http://hackage.haskell.org/package/microlens-contra
microlens-contra>.

If you haven't ever used lenses before, read
<http://hackage.haskell.org/package/lens-tutorial/docs/Control-Lens-Tutorial.html
this tutorial>. (It's for lens, but it applies to microlens just as well.)

Note that microlens has no dependencies starting from GHC 7.10 (base-4.8).
Prior to that, it depends on transformers-0.2 or above.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development files.


%prep
%setup -q -n %{pkgver}


%build
%ghc_lib_build


%install
%ghc_lib_install


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%license LICENSE


%files devel -f %{name}-devel.files
%doc CHANGELOG.md


%changelog
* Wed Jul 26 2017 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.4.8.0-1
- spec file generated by cabal-rpm-0.11.1
