# generated by cabal-rpm-0.11.1
# https://fedoraproject.org/wiki/Packaging:Haskell

Name:           hsc2hs
Version:        0.68.2
Release:        1%{?dist}
Summary:        A preprocessor that helps with writing Haskell bindings to C code

License:        BSD
Url:            https://hackage.haskell.org/package/%{name}
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-process-devel
# End cabal-rpm deps

%description
The hsc2hs program can be used to automate some parts of the process of writing
Haskell bindings to C code. It reads an almost-Haskell source file with
embedded special constructs, and outputs a real Haskell file with these
constructs processed, based on information taken from some C headers.
The extra constructs provide Haskell counterparts of C types, values of C
constants, including sizes of C types, and access to fields of C structs.

For more details, see the
<http://downloads.haskell.org/~ghc/master/users-guide/utils.html#writing-haskell-interfaces-to-c-code-hsc2hs
hsc2hs section> in the GHC User's Guide.


%prep
%setup -q


%build
%ghc_bin_build


%install
%ghc_bin_install


%files
%license LICENSE
%doc changelog.md
%{_bindir}/%{name}
%{_datadir}/%{name}-%{version}


%changelog
* Tue Jul 25 2017 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.68.2-1
- spec file generated by cabal-rpm-0.11.1
