# generated by cabal-rpm-0.11.1
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name hspec-discover
%global pkgver %{pkg_name}-%{version}

%bcond_with tests

Name:           ghc-%{pkg_name}
Version:        2.4.4
Release:        2%{?dist}
Summary:        Automatically discover and run Hspec tests

License:        MIT
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  chrpath
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-filepath-devel
%if %{with tests}
BuildRequires:  ghc-hspec-meta-devel
%endif
# End cabal-rpm deps

%description
Automatically discover and run Hspec tests


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development files.


%prep
%setup -q -n %{pkgver}


%build
%ghc_lib_build


%install
%ghc_lib_install
%ghc_fix_rpath %{pkgver}


%check
%cabal_test


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%license LICENSE


%files devel -f %{name}-devel.files
%{_bindir}/%{pkg_name}


%changelog
* Fri Nov 10 2017 David Shea <dshea@redhat.com> - 2.4.4-2
- Remove the URL from the %%description

* Fri Jul 28 2017 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 2.4.4-1
- spec file generated by cabal-rpm-0.11.1
